MAP_CLIENT_NAME = 'xpath://div[@class="user-context-menu-info__name"]'
MAP_MENU_OPTION_ACCOUNTS = '//li[@class="bb-navigation__item"]//child::a[@href="#/contas"]'
MAP_MENU_OPTION_CARDS = '//li[@class="bb-navigation__item"]//child::a[@href="#/cartoes"]'
MAP_MENU_OPTION_SOCIAL_SECURITY = '//li[@class="bb-navigation__item"]//child::a[@href="#/taxa-social-unica"]'
MAP_MENU_OPTION_SERVICES = '//li[@class="bb-navigation__item"]//child::a[@href="#/servicos"]'
