MAP_WELCOME_MESSAGE = 'xpath://h1[@id="kc-page-title"]'
MAP_INVALID_CREDENTIAL_MESSAGE = 'xpath://label[@class="kc-feedback-text"]'
MAP_USERNAME = 'xpath://input[@id="username"]'
MAP_PASSWORD = 'xpath://input[@id="password"]'
MAP_LOGIN_BUTTON = 'xpath://input[@id="kc-login"]'
