MAP_SCREEN_NAME = 'xpath://h1[contains(text(), "Contas internacionais")]'

#International Accounts Main Screen
MAP_INTER_ACC_TRANSF_MAIN_ORIGIN_ACCOUNT_LIST = 'xpath://span[@class="ng-arrow-wrapper"]'
MAP_INTER_ACC_TRANSF_MAIN_FIRST_ORIGIN_ACCOUNT = 'xpath://div[@class="bb-product-item bb-product-item-basic-account-ui product-item"]//div//div//div//div[1]//div[2]//bb-ellipsis-ui/div'
MAP_INTER_ACC_TRANSF_MAIN_ORIGIN_ACCOUNT_SELECTED = 'xpath://div[@class="bb-product-item bb-product-item-basic-account-ui product-item active"]//div//div//div//div[1]//div[2]//bb-ellipsis-ui/div'
MAP_INTER_ACC_TRANSF_MAIN_DESTINATION_ACCOUNT_LIST = 'xpath://button[@class="dropdown-toggle btn-outline-secondary btn btn-md"]'
MAP_INTER_ACC_TRANSF_MAIN_DESTINATION_ACCOUNT_SELECTED = 'xpath://bb-beneficiary-selector-contact[1]//button[@type="button"]'
MAP_INTER_ACC_TRANSF_MAIN_IBAN = 'xpath://input[@id="bb_input_2"]'
MAP_INTER_ACC_TRANSF_MAIN_ALERT_MSG = 'xpath://cgd-payment-info-message'
MAP_INTER_ACC_TRANSF_MAIN_INTEGER_AMOUNT = 'xpath://input[@id="bb_element_14"]'
MAP_INTER_ACC_TRANSF_MAIN_DECIMAL_AMOUNT = 'xpath://input[@id="bb_element_12"]'
MAP_INTER_ACC_TRANSF_MAIN_DESCRIPTION = 'xpath://textarea[@id="bb_input_5"]'
MAP_INTER_ACC_TRANSF_MAIN_NORMAL_TRANSF_TYPE = 'xpath://input[@value="normal"]//ancestor::label[@data-role="radio-group-option"]'
MAP_INTER_ACC_TRANSF_MAIN_CALENDAR = 'xpath://button[@class="bb-input-datepicker__calendar-opener-button btn-link btn btn-md"]'
MAP_INTER_ACC_TRANSF_MAIN_SCHEDULED_DATE = 'xpath://time[@datetime="26/10/2021"]'
MAP_INTER_ACC_TRANSF_MAIN_CONFIRMATION_BUTTON = 'xpath://span[@class="bb-load-button__content"]'

#International Accounts Review Screen
MAP_INTER_ACC_TRANSF_REVIEW_ORIGIN_ACCOUNT_LIST = 'xpath://span[@class="ng-arrow-wrapper"]'
MAP_INTER_ACC_TRANSF_REVIEW_FIRST_ORIGIN_ACCOUNT = 'xpath://div[@class="bb-product-item bb-product-item-basic-account-ui product-item"]//div//div//div//div[1]//div[2]//bb-ellipsis-ui/div'
MAP_INTER_ACC_TRANSF_REVIEW_ORIGIN_ACCOUNT_SELECTED = 'xpath://div[@class="bb-product-item bb-product-item-basic-account-ui product-item active"]//div//div//div//div[1]//div[2]//bb-ellipsis-ui/div'
MAP_INTER_ACC_TRANSF_REVIEW_DESTINATION_ACCOUNT_LIST = 'xpath://button[@class="dropdown-toggle btn-outline-secondary btn btn-md"]'
MAP_INTER_ACC_TRANSF_REVIEW_DESTINATION_ACCOUNT_SELECTED = 'xpath://bb-beneficiary-selector-contact[1]//button[@type="button"]'
MAP_INTER_ACC_TRANSF_REVIEW_IBAN = 'xpath://input[@id="bb_input_2"]'
MAP_INTER_ACC_TRANSF_REVIEW_ALERT_MSG = 'xpath://cgd-payment-info-message'
MAP_INTER_ACC_TRANSF_REVIEW_INTEGER_AMOUNT = 'xpath://input[@id="bb_element_14"]'
MAP_INTER_ACC_TRANSF_REVIEW_DECIMAL_AMOUNT = 'xpath://input[@id="bb_element_12"]'
MAP_INTER_ACC_TRANSF_REVIEW_DESCRIPTION = 'xpath://textarea[@id="bb_input_5"]'
MAP_INTER_ACC_TRANSF_REVIEW_NORMAL_TRANSF_TYPE = 'xpath://input[@value="normal"]//ancestor::label[@data-role="radio-group-option"]'
MAP_INTER_ACC_TRANSF_REVIEW_CALENDAR = 'xpath://button[@class="bb-input-datepicker__calendar-opener-button btn-link btn btn-md"]'
MAP_INTER_ACC_TRANSF_REVIEW_SCHEDULED_DATE = 'xpath://time[@datetime="26/10/2021"]'
MAP_INTER_ACC_TRANSF_REVIEW_CONFIRMATION_BUTTON = 'xpath://span[@class="bb-load-button__content"]'
