MAP_SCREEN_NAME = 'xpath://h1[contains(text(), "Contas internacionais")]'

#International Accounts Main Screen
MAP_INTER_ACC_TRANSF_MAIN_ORIGIN_ACCOUNT_LIST = 'xpath://span[@class="ng-arrow-wrapper"]'
MAP_INTER_ACC_TRANSF_MAIN_FIRST_ORIGIN_ACCOUNT = 'xpath://div[@class="bb-product-item bb-product-item-basic-account-ui product-item"]//div//div//div//div[1]//div[2]//bb-ellipsis-ui/div'
MAP_INTER_ACC_TRANSF_MAIN_ORIGIN_ACCOUNT_SELECTED = 'xpath://div[@class="bb-product-item bb-product-item-basic-account-ui product-item active"]//div//div//div//div[1]//div[2]//bb-ellipsis-ui/div'
MAP_INTER_ACC_TRANSF_MAIN_DESTINATION_ACCOUNT_LIST = 'xpath://button[@class="dropdown-toggle btn-outline-secondary btn btn-md"]'
MAP_INTER_ACC_TRANSF_MAIN_DESTINATION_ACCOUNT_SELECTED = 'xpath://bb-beneficiary-selector-contact[1]//button[@type="button"]'
MAP_INTER_ACC_TRANSF_MAIN_DESTINATION_ACCOUNT_IBAN = 'xpath://input[@id="bb_input_2"]'
MAP_INTER_ACC_TRANSF_MAIN_ALERT_MSG = 'xpath://cgd-payment-info-message'
MAP_INTER_ACC_TRANSF_MAIN_INTEGER_AMOUNT = 'xpath://input[@id="bb_element_14"]'
MAP_INTER_ACC_TRANSF_MAIN_DECIMAL_AMOUNT = 'xpath://input[@id="bb_element_12"]'
MAP_INTER_ACC_TRANSF_MAIN_DESCRIPTION = 'xpath://textarea[@id="bb_input_5"]'
MAP_INTER_ACC_TRANSF_MAIN_NORMAL_TRANSF_TYPE = 'xpath://input[@value="normal"]//ancestor::label[@data-role="radio-group-option"]'
MAP_INTER_ACC_TRANSF_MAIN_SCHEDULED_DATE = 'xpath://input[@id="bb_input_7"]'
MAP_INTER_ACC_TRANSF_MAIN_CONFIRMATION_BUTTON = 'xpath://span[@class="bb-load-button__content"]'

#International Accounts Review Screen
MAP_INTER_ACC_TRANSF_REVIEW_IBAN_FROM = 'xpath://div[@class="position-relative"]//fieldset//div[1]//div[1]//span[3]'
MAP_INTER_ACC_TRANSF_REVIEW_IBAN_DESTINATION = 'xpath://div[@class="position-relative"]//fieldset//div[1]//div[1]//span[3]'
MAP_INTER_ACC_TRANSF_REVIEW_INTEGER_AMOUNT = 'xpath://bb-amount-ui[@class="payment-amount"]//span//span//span[2]'
MAP_INTER_ACC_TRANSF_REVIEW_DECIMAL_AMOUNT = 'xpath://bb-amount-ui[@class="payment-amount"]//span//span//span[4]'
MAP_INTER_ACC_TRANSF_REVIEW_DESCRIPTION = 'xpath://div[@class="position-relative"]//fieldset//div[4]//div//div[2]'
MAP_INTER_ACC_TRANSF_REVIEW_TRANSF_TYPE = 'xpath://div[@class="position-relative"]//fieldset//div[4]/div[2]/div[2]'
MAP_INTER_ACC_TRANSF_REVIEW_START_DATE = 'xpath://div[@class="position-relative"]//fieldset//div[5]/div[2]/span[2]'
MAP_INTER_ACC_TRANSF_REVIEW_END_DATE = 'xpath://div[@class="position-relative"]//fieldset//div[6]/div[1]/span[2]'
MAP_INTER_ACC_TRANSF_REVIEW_CONFIRMATION_BUTTON = 'xpath://button[@class="bb-button-bar__button btn btn-primary btn-md"]'
