*** Settings ***


Library         SeleniumLibrary
Library         BuiltIn

Variables       ../element_mapping/TransfersPage_mapping.py

Variables       ../data/TransfersPage_data.py



*** Keywords ***

Verify if the values on the International Account review page are the same as the IACC main page

    Wait until element is visible   ${MAP_INTER_ACC_TRANSF_REVIEW_IBAN_FROM}   10
    ${VAR_INTER_ACC_TRANSF_REVIEW_IBAN_FROM}   Get Text  ${MAP_INTER_ACC_TRANSF_REVIEW_IBAN_FROM}
    Should Be Equal As Strings    ${VAR_INTER_ACC_TRANSF_REVIEW_IBAN_FROM}    ${VAR_INTER_ACC_TRANSF_MAIN_ORIGIN_ACCOUNT_SELECTED}

    Wait until element is visible   ${MAP_INTER_ACC_TRANSF_REVIEW_IBAN_DESTINATION}  10
    ${VAR_INTER_ACC_TRANSF_REVIEW_IBAN_DESTINATION}  Get Text  ${MAP_INTER_ACC_TRANSF_REVIEW_IBAN_DESTINATION}
    Should Be Equal As Strings    ${VAR_INTER_ACC_TRANSF_REVIEW_IBAN_DESTINATION}    ${VAR_INTER_ACC_TRANSF_MAIN_ORIGIN_ACCOUNT_SELECTED}

    Wait until element is visible   ${MAP_INTER_ACC_TRANSF_REVIEW_INTEGER_AMOUNT}   10
    ${VAR_INTER_ACC_TRANSF_REVIEW_INTEGER_AMOUNT}   Get Text  ${MAP_INTER_ACC_TRANSF_REVIEW_INTEGER_AMOUNT}
    ${VAR_INTER_ACC_TRANSF_REVIEW_INTEGER_AMOUNT}   Remove String  ${VAR_INTER_ACC_TRANSF_REVIEW_INTEGER_AMOUNT}   .
    Should Be Equal As Strings  ${VAR_INTER_ACC_TRANSF_REVIEW_INTEGER_AMOUNT}   ${DATA_INTER_ACC_TRANSF_MAIN_INTEGER_AMOUNT}

    Wait until element is visible   ${MAP_INTER_ACC_TRANSF_REVIEW_DECIMAL_AMOUNT}   10
    ${VAR_INTER_ACC_TRANSF_REVIEW_DECIMAL_AMOUNT}   Get Text  ${MAP_INTER_ACC_TRANSF_REVIEW_DECIMAL_AMOUNT}
    Should Be Equal As Strings  ${VAR_INTER_ACC_TRANSF_REVIEW_DECIMAL_AMOUNT}   ${DATA_INTER_ACC_TRANSF_MAIN_DECIMAL_AMOUNT}

    Wait until element is visible   ${MAP_INTER_ACC_TRANSF_REVIEW_DESCRIPTION}   10
    ${VAR_INTER_ACC_TRANSF_REVIEW_DESCRIPTION}   Get Text  ${MAP_INTER_ACC_TRANSF_REVIEW_DESCRIPTION}
    Should Be Equal As Strings  ${VAR_INTER_ACC_TRANSF_REVIEW_DESCRIPTION}   ${DATA_INTER_ACC_TRANSF_MAIN_DESCRIPTION}

    Wait until element is visible   ${MAP_INTER_ACC_TRANSF_REVIEW_TRANSF_TYPE}  10
    ${VAR_INTER_ACC_TRANSF_REVIEW_TRANSF_TYPE}  Get Text  ${MAP_INTER_ACC_TRANSF_REVIEW_TRANSF_TYPE}
    Should Be Equal As Strings  ${VAR_INTER_ACC_TRANSF_REVIEW_TRANSF_TYPE}   Normal

    Wait until element is visible   ${MAP_INTER_ACC_TRANSF_REVIEW_START_DATE}  10
    ${VAR_INTER_ACC_TRANSF_REVIEW_START_DATE}  Get Text  ${MAP_INTER_ACC_TRANSF_REVIEW_START_DATE}
    Should Be Equal As Strings  ${VAR_INTER_ACC_TRANSF_REVIEW_START_DATE}   ${DATA_INTER_ACC_TRANSF_MAIN_SCHEDULED_DATE}

    Wait until element is visible   ${MAP_INTER_ACC_TRANSF_REVIEW_END_DATE}  10
    ${VAR_INTER_ACC_TRANSF_REVIEW_END_DATE}  Get Text  ${MAP_INTER_ACC_TRANSF_REVIEW_END_DATE}
    Should Be Equal As Strings  ${VAR_INTER_ACC_TRANSF_REVIEW_END_DATE}   ${DATA_INTER_ACC_TRANSF_MAIN_SCHEDULED_DATE}
